# -*- coding: utf-8 -*-
"""Copy of code2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeFcIi81w7RSFVhxaZgaflNF6t2prYgj
"""

import locale
locale.getpreferredencoding = lambda: "UTF-8"

!pip install roboflow


from roboflow import Roboflow
rf = Roboflow(api_key="BhJ63IemG3ACRXXxUyzC")
project = rf.workspace("dental-decay").project("check-hfbzl-zemwx")
version = project.version(18)
dataset = version.download("yolov8")

!pip install ultralytics

from ultralytics import YOLO

model = YOLO('yolov8n-seg.pt')

model=YOLO('yolov8n-seg.pt')

model.train(data="/content/CHECK-18/data.yaml")
train_prams ={'epochs':100,
             'imgsz':640,
             'batch':32,
             'workers':2,
             'device':0,
            'cls-pw': {1.0,1.5,2.0}}

model.predict('/content/CHECK-18/test/images/132_jpg.rf.e5f22415915c13dc9bad062f8c2fe09b.jpg',save=True , conf=0.30)